### PR TITLE
added Dockerfile for deployment in Docker

### PR DESCRIPTION
**Pull request by cchriso**

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
lol was just about to contribute this (cloned like an hour ago). good job.

**Comment by mathematicalmichael** [comment]
@char if you're unfamiliar with dockerfiles, you can rest assured that this is a great implementation. definitely hit merge. I'd be happy to contribute more instructions to the README to reflect how to use it.

**Comment by voidstar0** [comment]
Thank you so much for this!

**Comment by mathematicalmichael** [comment]
if #17 gets merged, can use the same `requirements.txt` for the Dockerfile.

**Pull request merged**
