### PR TITLE
Multiple changes to the bot, should be clearer now

### PR DESCRIPTION
**Pull request by mehdichekori**
Added a random wait time to reduce the times Instagram blocks the accounts from commenting
Added multiple comments
Added colorIt library for clarity
Removed the env variable (wasn't working for me)
Changed the exception catcher

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
i think you need to copy `.env.example` to `.env` and edit yourself, avoids accidental commits of info.

**Comment by mehdichekori** [comment]
Thanks!

**Comment by syntax** [comment]
random wait time is probably a very suitable/smart implementation for stopping the rate limit tbh!

**Comment by mehdichekori** [comment]
Re-added the reference to the .env file,
Added the rate limiter that was implemented in the master

**Comment by mathematicalmichael** [comment]
> random wait time is probably a very suitable/smart implementation for stopping the rate limit tbh!

I just added `time.sleep(random.randint(1,10))` to the bottom of the `try` block and it helped, but didn't fix entirely.

**Comment by voidstar0** [comment]
Thank you so much for this!

**Pull request merged**
